export { default as fallback } from "./fallback.svg";
export { default as settings } from "./settings.svg";
export { default as dashboard } from "./dashboard.svg";
export { default as logo } from "./logo.svg";
export { default as bell } from "./bell.svg";
export { default as search } from "./search.svg";
export { default as plus } from "./plus.svg";
export { default as payment } from "./payment.svg";
export { default as logout } from "./logout.svg";